apiVersion: v1
kind: Service
metadata:
  name: bookstore-backend-service
spec:
  selector:
    app: bookstore-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
